# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Upload Tar Artifact"
description: "Upload an artifact and zips it as {name}.tar.gz"
inputs:
  name:
    description: "Name for artifact"
    required: true
  path:
    description: "Path to zip"
    required: true
runs:
  using: "composite"
  steps:
    - name: 📦 Pack build as tar
      run: tar -czf ${{ inputs.name }} ${{ inputs.path }}
      shell: bash

    - name: ⬆ Upload build
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}
