# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⚡ Run Test
        run: npm run test

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
