# SPDX-FileCopyrightText: 2025 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Dependency Review"
on:
  workflow_call:

jobs:
  dependency-review:
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v4
      - name: 🔎 Dependency Review
        uses: actions/dependency-review-action@v4
