---
name: Cleans all preview pages for gh-pages

on: [push]
#    branches:
#      - main

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 📥 Get gh-pages tar
        run: wget -q https://github.com/db-ui/base/tarball/gh-pages

      - name: ➕ Create public dir
        run: mkdir public

      - name: 📦 Unpack Tar
        run: tar -zxf gh-pages -C public --strip-components 1

      - name: 🗑️ Clean all preview pages
        id: cleanup
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./.github/scripts/cleanup-gh-pages.js')
            return await script({github, context})

      - name: 📰 Print cleanup messages
        run: echo ${{steps.cleanup.outputs.result}}

      - name: 🥅 Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
