name: Default push workflow

on:
  pull_request:
  push:
    branches:
      - "main"
      - "dbux-3"

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    if: github.event.pull_request.head.repo.owner.login == 'db-ui' || github.event.pull_request == null"
    uses: ./.github/workflows/00-scan-secrets.yml

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]

  # TODO: Reactivate when test works
  #  test:
  #    uses: ./.github/workflows/01-test.yml
  #    needs: [init]

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]

  checks-done:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Checks done
        run: echo "🎉 Linting & build were successful."
    needs: [build, lint]

  deploy:
    uses: ./.github/workflows/02-deploy-gh-pages.yml
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.owner.login == 'db-ui' || github.event.pull_request == null" }}
    needs: [lint, build]
