name: Default push workflow

on:
  pull_request:
  push:
    branches:
      - "main"
      - "dbux-3"

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  scan-secrets:
    if: github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui'
    uses: ./.github/workflows/00-scan-secrets.yml

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]

  # TODO: Reactivate when test works
  #  test:
  #    uses: ./.github/workflows/01-test.yml
  #    needs: [init]

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]

  checks-done:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Checks done
        run: |
          resultBuild="${{ needs.build.result }}"
          resultLint="${{ needs.lint.result }}"
          if [[ $resultBuild == "success" && $resultLint == "success" ]]; then
            echo "🎉 Linting & build were successful."
            exit 0
          else
            echo "There have been problems with the Cypress tests."
            exit 1
          fi
    needs: [build, lint]

  deploy:
    uses: ./.github/workflows/02-deploy-gh-pages.yml
    if: ${{ github.actor != 'dependabot[bot]' && (github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui') }}
    needs: [lint, build]
