---
name: Default On-Pull-Request

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  auto-merge:
    uses: ./.github/workflows/99-auto-merge.yml

  codeql:
    uses: ./.github/workflows/99-codeql-analysis.yml

  dependency-review:
    uses: ./.github/workflows/99-dependency-review.yml

  labeler:
    if: github.event.pull_request.head.repo.owner.login == 'db-ui' || github.event.pull_request == null"
    uses: ./.github/workflows/99-labeler.yml
